config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users
  root 'pages#home'
  resources :turmas do 
  	collection do
  		post :add_aluno
  		post :add_attributes
  	end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turma.rb
class Turma < ApplicationRecord

	has_and_belongs_to_many :users

	has_attached_file :image, styles: { medium: "150x150>", thumb: "100x100>", small: "150x150>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	validates :user, presence: true
	validates :conteudo, presence: true, length: {maximum: 140}

	has_attached_file :photo, :styles => {:small => "150x150"}
	do_not_validate_attachment_file_type :photo
	
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_and_belongs_to_many :turmas
  has_one :user_attribute
end

app/models/user_attribute.rb
class UserAttribute < ApplicationRecord
  belongs_to :user


  def add_attribute(attribute_name, amount)
  	amount = amount.to_i
  	case attribute_name
	when "money"
	  	self.money+=amount
	
	when "hp"
		self.hp += amount
	  	if self.hp >= 50
	  		self.hp = 50
	  	end
	  when "mana"
	  	self.mana += amount
	  	if self.hp >= 30 
	  		self.hp = 30
	  	end
	  when "xp"
	  	self.xp += amount
	  	upLevel = (self.xp / 1024).to_i
	  	self.xp = self.xp % 1024
	  	self.level += upLevel

	end

  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]



  def add_attributes
    aluno = User.find(params["user_id"])
    aluno.user_attribute.add_attribute(params['commit'], params['value'])

    aluno.user_attribute.save
    redirect_back(fallback_location: root_path, alert: "sucesso")

  end


  def add_aluno
    @turma = Turma.find(params[:turma_id])
    newAluno = User.find_by(email: params[:email])

    begin 
      @turma.users << newAluno
      @turma.save
      
      if newAluno.user_attribute.nil?
        newAluno.user_attribute = UserAttribute.new do | user_attributes |
          user_attributes.level = 1
          user_attributes.xp   = 0
          user_attributes.hp    = 50
          user_attributes.mana  = 30
          user_attributes.money = 50
        end 
      end


      message = "Aluno cadastrado com sucesso"
    rescue Exception => e
      e.message
      message = "Não foi possível cadastrar o aluno\r\n Error:  " + e.message + ")" 
    end

    redirect_back(fallback_location: root_path, alert: message)
    
  end



  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
    @turma = Turma.find(params[:id])
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turma_params
      params.require(:turma).permit(:nome, :inicio, :fim, :horas, :image)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)

      if @tweet.save
         redirect_to @tweet, notice: 'Tweet was successfully created.' 
      else
       render :new 
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    @tweet = current_user.tweets.find(params[:id])

      if @tweet.update(tweet_params)
        redirect_to @tweet, notice: 'Tweet was successfully updated.' 
      else
        render :edit 
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' 
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :conteudo, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassGeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "ClassGeek", root_path, class:"navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item active"> <%= link_to "Classes", turmas_path, class:"nav-link" %>  </li>
          <li class="nav-item active"> <%= link_to "Tweets", tweets_path, class:"nav-link" %>  </li>
          
            <% if !user_signed_in? %> 
                <li class="nav-item active"> <%= link_to "Register", new_user_registration_path, class:"nav-link" %>   </li>

                <li class="nav-item active"> <%= link_to "Login", new_user_session_path, class:"nav-link" %>   </li>
            <% else %>
                <li class="nav-item active"> <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>   </li>
            <% end %>

        </ul>
          
        
    </div>      
    </nav>
      
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class:"alert alert-info #{name}") %>
    <% end %>  
      
      
    <div class="container"> <%= yield %> </div>   
     
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :inicio %>
    <%= form.datetime_select :inicio %>
  </div>

  <div class="field">
    <%= form.label :fim %>
    <%= form.datetime_select :fim %>
  </div>

  <div class="field">
    <%= form.label :horas %>
    <%= form.text_field :horas %>
  </div>

  <div class="field">
    <%= form.label :exp %>
    <%= form.text_field :exp %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/_student_attributes.html.erb
<div class="card">
	  <div class="card-body">
	    <b> <%= aluno.name %> </b>
	    <small>@<%= aluno.username %></small>
		

		<%= form_for (aluno.user_attribute), :url => add_attributes_turmas_path, :html =>{:method => :post} do | f |%>
			<%= hidden_field_tag :user_id, aluno.id%>

			<div class="row"> 
				<div class="col">
					<%= f.submit "xp", class: "xp button" %> <br> <%= aluno.user_attribute.level %>/
		   			 <%= aluno.user_attribute.xp %>
				</div>

				<div class="col">
					<%= f.submit "hp", class: "hp button" %> <br>
					<b> Hp: </b> <%= aluno.user_attribute.hp %>
				</div>
				<div class="col">
					<%= f.submit "money", class: "money button" %> <br>
					<b> Money: </b> <%= aluno.user_attribute.money  %>
				</div>
				<div class="col">
					<%= f.submit "mana", class: "mana button" %> <br>
					<b> Mana: </b> <%= aluno.user_attribute.mana %>
				</div>
				<div class="col">
					<%= text_field_tag :value, " ", class: "form-control" %>
				</div>

			</div>
		<% end %>



	    
	    
	  </div>
</div>	

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>
<div><%= link_to 'Cadastrar turma', new_turma_path, class:"btn btn-light" %> </div> <br>


  
    <% @turmas.each do |turma| %>
      <ul class='list-group'>
        <li class='list-group-item'>
          <%= image_tag(turma.image.url, :width => 40) if turma.image.present? %>
          <br>
          <h6> <%= turma.nome %> </h6> 
          <small> Inicio: <%= turma.inicio.strftime("%d/%m/%Y") %> </small> 
          <small> Termino: <%= turma.fim.strftime("%d/%m/%Y") %> </small>
          <div align='right'>
            <%= link_to 'Show', turma, class:"btn btn-light" %>
            <%= link_to 'Edit', edit_turma_path(turma), class:"btn btn-light" %>
            <%= link_to 'Destroy', turma, class:"btn btn-light",  method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </li>



      </ul>

    <% end %>

<br>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">

	<!-- turma -->
	<div class="col-4">
		<div class="card" style="width: 20rem;">
		  
		  <div class="card-body">
		  	<%= image_tag @turma.image.url(:medium) %>
		    <h5 class="card-title"> <%= @turma.nome %> </h5>
		    <p class="card-text"> Inicio: <%= @turma.inicio %> </p>
		    <a href="#" class="btn btn-primary">Go somewhere</a>
		  </div>
		</div>
	</div>



	<!-- alunos -->
	<div class="col-8">
			<div class="card">
			  <div class="card-body">
			
			<!-- card individul alunos -->	
			<% @turma.users.each do |aluno| %>	
				<%= render :partial => "student_attributes", :locals => {:aluno => aluno} %>			    
			<% end %>	  
			  
			  </div>
			</div>		

		<%= form_tag add_aluno_turmas_path(@turma), :method => :post do %>
			<%= email_field_tag :email, "",placeholder: 'email@email.com'%>
			<%= hidden_field_tag :turma_id, @turma.id %>
			<%= submit_tag "Cadastrar" %>
		<% end %>

	</div>



</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
 <br>
  <div class="form-group">
    
    <%= form.text_area :conteudo, class: "form-control", placeholder:"Novo tweet" %> 
  </div>

  <%= form.label :photo, 'Imagem', class:'glyphicon glyphicon-camera' %>  
  <%= form.file_field :photo %> 

  <%= form.submit "Enviar", class: "btn btn-primary", style:'margin-left:14rem'%>

 

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="container"> 


    <div>
      
      <div class="row">
        <div class="col-4">
          
          <div class="card" style="width: 15rem;">
              <% url = Gravatar.new(current_user.email).image_url %>
              <center><%= image_tag url, class: 'card-img-top rounded', style: "width: 13rem; margin-top:1rem" %> </center>
              <div class="card-body">
                <h5 class="card-title"> <%= current_user.name  %> </h5>
                <p class="card-text"></p>
                <%= link_to  "@#{current_user.username}", edit_user_registration_path, class: "badge badge-pill badge-dark" %>
              </div>
          </div>    


        </div>

        
        <div class="col-8">
            

          <ul class="list-group">
            <%= render 'form', tweet: @tweet %>
            <br>  
            <% @tweets.order(id: :desc).each do |tweet| %>             
              <%= link_to tweet, class:"list-group-item list-group-item-action"  do  %>
                <h6 class="list-group-heading"> 
                  <b> @<%= tweet.user.username %>  - </b>
                  <small> <%= tweet.user.name %> </small>
                </h6>
                
                <table class=" table"> 
                  <t4>
                   <p class="list-group-text"><%= tweet.conteudo %></p>
                    
                 </tr>
                 <% if tweet.photo.file? %>
                      <tr>  <%= image_tag tweet.photo.url, class:"card-img-top mx-auto", style:"width:30%;" %> </tr>
                  <% end %>


                </table>
                <small class="list-group-text">(<%= tweet.created_at.strftime("%d/%m/%Y - %H:%M") %>)</small> 
                

              <%end%>
              <br>
            <% end %>
          </ul> 
                    

        </div>
      </div>

  </div>

  
 
          

     



    

</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<center>

	<div class="card" style="width: 40rem;">
		<% if @tweet.photo.file? %>
			<%= image_tag @tweet.photo.url, class:"card-img-top mx-auto", style:"width:30%;" %>
		<%end%>
		<div class="card-body">
		  	<h4 class="card-title"><%= @tweet.user.email %> </h4>
		    <p class="card-text"><%= @tweet.conteudo %></p>
		    <p class="card-text">(<%= @tweet.created_at.strftime("%d/%m/%Y - %H:%M") %>)</p>	

		    <%= link_to 'Voltar', tweets_path %> |

		    <% if @tweet.user == current_user%>
		    	<%= link_to 'Editar', edit_tweet_path(@tweet) %> |
		    	<%= link_to 'Deletar', @tweet, method: :delete, data: { confirm: "você tem certeza que deseja apagar?"} %> 
		    <%end%>


  		</div>
</center>


	
	



</div>